[package]
name = "ggml"
version = { workspace = true }
edition = "2021"

[dependencies]
ggml-sys = { path = "../ggml-sys" }

log = { workspace = true }

thiserror = "1.0"

[dev-dependencies]
llm-base = { path = "../llm-base" }
