[package]
name = "llama-rs"
version = { workspace = true }
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggml = { path = "../ggml" }

bytemuck = "1.13.1"
partial_sort = "0.2.0"
thiserror = "1.0"
rand = { workspace = true }
serde = { version = "1.0.156", features = ["derive"] }
serde_bytes = "0.11"
bincode = "1.3.3"
serde_json = "1.0.94"
serde-pickle = "1.1.1"
protobuf = "= 2.14.0"
rust_tokenizers = "3.1.2"