[package]
name = "llm"
version = { workspace = true }
edition = "2021"

[dependencies]
llm-base = { path = "../llm-base" }
llm-llama = { path = "../models/llama", features = ["convert", "quantize"], optional = true }
llm-gpt2 = { path = "../models/gpt2", optional = true }
llm-bloom = { path = "../models/bloom", optional = true }

[features]
default = ["llama", "gpt2", "bloom"]
llama = ["dep:llm-llama"]
gpt2 = ["dep:llm-gpt2"]
bloom = ["dep:llm-bloom"]
