[package]
name = "llm"
version = { workspace = true }
edition = "2021"

[dependencies]
llm-base = { path = "../llm-base" }
llm-llama = { path = "../models/llama", features = ["convert"], optional = true }
llm-gpt2 = { path = "../models/gpt2", optional = true }
llm-gptj = { path = "../models/gptj", optional = true }
llm-bloom = { path = "../models/bloom", optional = true }
llm-neox = { path = "../models/neox", optional = true }

[features]
default = ["llama", "gpt2", "gptj", "bloom", "neox"]
llama = ["dep:llm-llama"]
gpt2 = ["dep:llm-gpt2"]
gptj = ["dep:llm-gptj"]
bloom = ["dep:llm-bloom"]
neox = ["dep:llm-neox"]
